rabbit2:
  image: hibadkin/rabbitmq-cluster-docker
  hostname: rabbit2
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
    - "4369:4369"
    - "5673:5672"
    - "15673:15672"
    - "25672:25672"
    - "9100"
    - "9101"
    - "9102"
    - "9103"
    - "9104"
    - "9105"
