rabbit2:
  image: hibadkin/rabbitmq-cluster-docker 
  hostname: rabbit2
  environment:
   - CLUSTERED=true                       #配置集群
   - CLUSTER_WITH=rabbit1                 #集群链接结点
   - RAM_NODE=true
  ports:                                  #暴露端口
    - "4369:4369"
    - "5673:5672"
    - "15673:15672"
    - "25672:25672"
    - "9100"
    - "9101"
    - "9102"
    - "9103"
    - "9104"
    - "9105"
  extra_hosts:
    - "rabbit1:139.59.240.247"
    - "rabbit3:188.166.183.42"
